name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material- 
      - run: pip install mkdocs-material==9.5.20
      - run: pip install mkdocs-material-extensions==1.3.1
      - run: pip install mkdocstrings==0.25.0
      - run: pip install mkdocstrings-python==1.10.8
      - run: pip install mkdocs-macros-plugin==1.0.1
      - run: mkdocs gh-deploy --force